#include "./ctype.h"

int character_class_map[128] = {
	// null
    ['\0'] = CC_NULL,
	
	// space
	['\t'] = CC_SPACE,
	['\n'] = CC_SPACE,
	['\v'] = CC_SPACE,
	['\f'] = CC_SPACE,
	['\r'] = CC_SPACE,
	[' '] = CC_SPACE,
	
	// punct
	['!'] = CC_PUNCT,
	['"'] = CC_PUNCT,
	['#'] = CC_PUNCT,
	['$'] = CC_PUNCT,
	['%'] = CC_PUNCT,
	['&'] = CC_PUNCT,
	['\''] = CC_PUNCT,
	['('] = CC_PUNCT,
	[')'] = CC_PUNCT,
	['*'] = CC_PUNCT,
	['+'] = CC_PUNCT,
	[','] = CC_PUNCT,
	['-'] = CC_PUNCT,
	['.'] = CC_PUNCT,
	['/'] = CC_PUNCT,
	[':'] = CC_PUNCT,
	[';'] = CC_PUNCT,
	['<'] = CC_PUNCT,
	['='] = CC_PUNCT,
	['>'] = CC_PUNCT,
	['?'] = CC_PUNCT,
	['@'] = CC_PUNCT,
	['['] = CC_PUNCT,
	[']'] = CC_PUNCT,
	['^'] = CC_PUNCT,
	['_'] = CC_PUNCT,
	['`'] = CC_PUNCT,
	['{'] = CC_PUNCT,
	['|'] = CC_PUNCT,
	['}'] = CC_PUNCT,
	['~'] = CC_PUNCT,
	
	// digit
    ['0'] = CC_DIGIT, 
    ['1'] = CC_DIGIT, 
    ['2'] = CC_DIGIT, 
    ['3'] = CC_DIGIT, 
    ['4'] = CC_DIGIT, 
    ['5'] = CC_DIGIT, 
    ['6'] = CC_DIGIT, 
    ['7'] = CC_DIGIT, 
    ['8'] = CC_DIGIT, 
    ['9'] = CC_DIGIT, 
	
	// alpha
	['A'] = CC_ALPHA,
	['B'] = CC_ALPHA,
	['C'] = CC_ALPHA,
	['D'] = CC_ALPHA,
	['E'] = CC_ALPHA,
	['F'] = CC_ALPHA,
	['G'] = CC_ALPHA,
	['H'] = CC_ALPHA,
	['I'] = CC_ALPHA,
	['J'] = CC_ALPHA,
	['K'] = CC_ALPHA,
	['L'] = CC_ALPHA,
	['M'] = CC_ALPHA,
	['N'] = CC_ALPHA,
	['O'] = CC_ALPHA,
	['P'] = CC_ALPHA,
	['Q'] = CC_ALPHA,
	['R'] = CC_ALPHA,
	['S'] = CC_ALPHA,
	['T'] = CC_ALPHA,
	['U'] = CC_ALPHA,
	['V'] = CC_ALPHA,
	['W'] = CC_ALPHA,
	['X'] = CC_ALPHA,
	['Y'] = CC_ALPHA,
	['Z'] = CC_ALPHA,
	['a'] = CC_ALPHA,
	['b'] = CC_ALPHA,
	['c'] = CC_ALPHA,
	['d'] = CC_ALPHA,
	['e'] = CC_ALPHA,
	['f'] = CC_ALPHA,
	['g'] = CC_ALPHA,
	['h'] = CC_ALPHA,
	['i'] = CC_ALPHA,
	['j'] = CC_ALPHA,
	['k'] = CC_ALPHA,
	['l'] = CC_ALPHA,
	['m'] = CC_ALPHA,
	['n'] = CC_ALPHA,
	['o'] = CC_ALPHA,
	['p'] = CC_ALPHA,
	['q'] = CC_ALPHA,
	['r'] = CC_ALPHA,
	['s'] = CC_ALPHA,
	['t'] = CC_ALPHA,
	['u'] = CC_ALPHA,
	['v'] = CC_ALPHA,
	['w'] = CC_ALPHA,
	['x'] = CC_ALPHA,
	['y'] = CC_ALPHA,
	['z'] = CC_ALPHA,
};
